### ISSUE TITLE
Error 'uninitialized constant Mime' in Rails 5.1/5.2

### ISSUE THREAD

**Issue by rlue** [Shopify/bootsnap#123]
Tried bootsnap in Rails 5.2rc1. Right out of the box, `rails s` threw this error:

```
$ rails s
/Users/rlue/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack/version.rb:2: warning: already initialized constant MessagePack::VERSION
/Users/rlue/.config/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack/version.rb:2: warning: previous definition of VERSION was here
/Users/rlue/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack/msgpack.bundle: warning: already initialized constant MessagePack::ExtensionValue
/Users/rlue/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack.rb:22: warning: already initialized constant MessagePack::DefaultFactory
/Users/rlue/.config/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack.rb:22: warning: previous definition of DefaultFactory was here
Traceback (most recent call last):
        56: from bin/rails:3:in `<main>'
        55: from bin/rails:3:in `load'
        54: from /Users/rlue/Sandbox/foo/bin/spring:15:in `<top (required)>'
        53: from /Users/rlue/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        52: from /Users/rlue/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        51: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        50: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        49: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        48: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        47: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        46: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        45: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        44: from /Users/rlue/Sandbox/foo/bin/rails:9:in `<top (required)>'
        43: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        42: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        41: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/commands.rb:18:in `<main>'
        40: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/command.rb:46:in `invoke'
        39: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/command/base.rb:65:in `perform'
        38: from /Users/rlue/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        37: from /Users/rlue/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        36: from /Users/rlue/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        35: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/commands/server/server_command.rb:142:in `perform'
        34: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/commands/server/server_command.rb:142:in `tap'
        33: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
        32: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        31: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        30: from /Users/rlue/Sandbox/foo/config/application.rb:3:in `<main>'
        29: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        28: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        27: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/all.rb:15:in `<main>'
        26: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/all.rb:15:in `each'
        25: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/all.rb:17:in `block in <main>'
        24: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        23: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        22: from /Users/rlue/.gem/ruby/2.5.0/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:12:in `<main>'
        21: from /Users/rlue/.gem/ruby/2.5.0/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:13:in `<module:ActiveStorage>'
        20: from /Users/rlue/.gem/ruby/2.5.0/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:14:in `<class:Engine>'
        19: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/engine.rb:385:in `isolate_namespace'
        18: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/railtie.rb:190:in `method_missing'
        17: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/railtie.rb:190:in `public_send'
        16: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/engine.rb:535:in `routes'
        15: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        14: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        13: from /Users/rlue/.gem/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/routing/route_set.rb:10:in `<main>'
        12: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        11: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        10: from /Users/rlue/.gem/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/request.rb:11:in `<main>'
         9: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
         8: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
         7: from /Users/rlue/.gem/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:3:in `<main>'
         6: from /Users/rlue/.gem/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:4:in `<module:ActionDispatch>'
         5: from /Users/rlue/.gem/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:5:in `<module:Http>'
         4: from /Users/rlue/.gem/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:11:in `<module:Parameters>'
         3: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
         2: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
         1: from /Users/rlue/.gem/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/mime_type.rb:8:in `<main>'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant': uninitialized constant Mime (NameError)
```

Tried in a brand new Rails 5.1 app, and got the same error with an extra backtrace:

```
liberte:bar rlue$ rails s
/Users/rlue/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack/version.rb:2: warning: already initialized constant MessagePack::VERSION
/Users/rlue/.config/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack/version.rb:2: warning: previous definition of VERSION was here
/Users/rlue/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack/msgpack.bundle: warning: already initialized constant MessagePack::ExtensionValue
/Users/rlue/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack.rb:22: warning: already initialized constant MessagePack::DefaultFactory
/Users/rlue/.config/.gem/ruby/2.5.0/gems/msgpack-1.2.2/lib/msgpack.rb:22: warning: previous definition of DefaultFactory was here
Traceback (most recent call last):
        39: from bin/rails:3:in `<main>'
        38: from bin/rails:3:in `load'
        37: from /Users/rlue/Sandbox/bar/bin/spring:15:in `<top (required)>'
        36: from /Users/rlue/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        35: from /Users/rlue/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        34: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        33: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        32: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        31: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        30: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        29: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        28: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        27: from /Users/rlue/Sandbox/bar/bin/rails:9:in `<top (required)>'
        26: from /Users/rlue/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
        25: from /Users/rlue/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
        24: from /Users/rlue/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
        23: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        22: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        21: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<main>'
        20: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
        19: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
        18: from /Users/rlue/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        17: from /Users/rlue/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        16: from /Users/rlue/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        15: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
        14: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
        13: from /Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
        12: from /Users/rlue/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
        11: from /Users/rlue/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
        10: from /Users/rlue/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
         9: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
         8: from /Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
         7: from /Users/rlue/Sandbox/bar/config/application.rb:7:in `<main>'
         6: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
         5: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
         4: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
         3: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
         2: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
         1: from /Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jbuilder'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Mime
Backtrace for gem load error is:
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/Users/rlue/.gem/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_dispatch/http/mime_type.rb:6:in `<main>'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/.gem/ruby/2.5.0/gems/jbuilder-2.7.0/lib/jbuilder/jbuilder_template.rb:2:in `<main>'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/.gem/ruby/2.5.0/gems/jbuilder-2.7.0/lib/jbuilder/railtie.rb:2:in `<main>'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/.gem/ruby/2.5.0/gems/jbuilder-2.7.0/lib/jbuilder.rb:324:in `<main>'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/rlue/Sandbox/bar/config/application.rb:7:in `<main>'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
/Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
/Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
/Users/rlue/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/rlue/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/rlue/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
/Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
/Users/rlue/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<main>'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/.config/.gem/ruby/2.5.0/bundler/gems/bootsnap-4d0b042b1f20/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/rlue/Sandbox/bar/bin/rails:9:in `<top (required)>'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Users/rlue/.config/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/rlue/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
/Users/rlue/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
/Users/rlue/Sandbox/bar/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Bunder Error Backtrace:
```

---

System:

* bootsnap `master` (commit 4d0b042)
* macOS 10.11 El Capitan
* Ruby 2.5.0
* Rails 5.1 / 5.2rc1
* chruby 0.3.9

**Comment by speedo-spin** [comment]
+1

**Comment by BalGuldur** [comment]
+1 Rails 5.2.0, Ruby 2.5.0, Jbuilder 2.7.0

**Comment by lhoeg** [comment]
+1 Rails 5.2.0.beta2/5.2.0.rc1/master Ruby 2.5.0p0, ruby-install + chruby 0.3.9, MacOS Sierra
Works with `rails new --skip-bootsnap`

**Comment by ojab** [comment]
Can you please check if https://github.com/Shopify/bootsnap/pull/136 fixes the issue? You can try it with `gem 'bootsnap', github: 'ojab/bootsnap', require: false` in Gemfile.

**Comment by lhoeg** [comment]
Yes, #136 fixes this for me :-)

**Comment by hansondr** [comment]
@ojab I can confirm #136 fixed this issue for me as well.

Ubuntu 17.10
Rails 5.2.0.rc1
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
rbenv 1.1.1-28-gb943955

**Comment by burke** [comment]
I bet this is fixed in version 1.2.0.pre, please let me know whether that fixes this issue or not.

**Comment by rlue** [comment]
Sorry @burke, didn't fix it for me. You can confirm yourself with

```
$ rails new foo && cd foo && sed -i '' '/bootsnap/s/1\.0/2.0pre/' Gemfile && bundle && rails s
```

FWIW, #136 did fix it for me, but I understand per the discussion there that there are edge cases yet to be resolved with it.

**Comment by rlue** [comment]
@wpolicarpo yes it does!

**Comment by burke** [comment]
1.3.0 is released, so I'll close this now. Thanks everyone!
