### ISSUE TITLE
Intermittent error "uninitialized constant Users" after rails server startup

### ISSUE THREAD

**Issue by sedubois** [Shopify/bootsnap#269]
Since upgrading our Rails app to 5.2.3 a few months ago and introducing Bootsnap (currently using v1.4.4), I have intermittent issues with `User` and `Admin` namespaces not found after starting the rails server on my dev machine and visiting our `/login`, `/signup` or `/admin` routes. The workaround is to reload the page or restart the server and eventually I'm able to visit those pages. The errors do not occur in test and production environments. 

Below is an example of error trace:
<details>

```
Started GET "/signup" for 127.0.0.1 at 2019-08-01 14:23:38 +0300
  
ActionController::RoutingError (uninitialized constant Users):
  
bootsnap (1.4.4) lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant'
bootsnap (1.4.4) lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
bootsnap (1.4.4) lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
bootsnap (1.4.4) lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
activesupport (5.2.3) lib/active_support/inflector/methods.rb:283:in `const_get'
activesupport (5.2.3) lib/active_support/inflector/methods.rb:283:in `block in constantize'
activesupport (5.2.3) lib/active_support/inflector/methods.rb:281:in `each'
activesupport (5.2.3) lib/active_support/inflector/methods.rb:281:in `inject'
activesupport (5.2.3) lib/active_support/inflector/methods.rb:281:in `constantize'
actionpack (5.2.3) lib/action_dispatch/http/request.rb:88:in `controller_class_for'
actionpack (5.2.3) lib/action_dispatch/http/request.rb:81:in `controller_class'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:46:in `controller'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.2.3) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (5.2.3) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:840:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack-pjax (1.1.0) lib/rack/pjax.rb:12:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
http_accept_language (2.1.1) lib/http_accept_language/middleware.rb:14:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
remotipart (1.4.3) lib/remotipart/middleware.rb:32:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/cookies.rb:670:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activerecord (5.2.3) lib/active_record/migration.rb:559:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
honeybadger (4.3.1) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (4.3.1) lib/honeybadger/agent.rb:345:in `with_rack_env'
honeybadger (4.3.1) lib/honeybadger/rack/error_notifier.rb:30:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
honeybadger (4.3.1) lib/honeybadger/rack/user_feedback.rb:31:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
honeybadger (4.3.1) lib/honeybadger/rack/user_informer.rb:21:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
webpacker (4.0.7) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
newrelic_rpm (6.4.0.356) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
puma (4.0.0) lib/puma/configuration.rb:228:in `call'
puma (4.0.0) lib/puma/server.rb:657:in `handle_request'
puma (4.0.0) lib/puma/server.rb:467:in `process_client'
puma (4.0.0) lib/puma/server.rb:328:in `block in run'
puma (4.0.0) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```
</details>

I would be grateful if someone would have an idea of the cause and how to fix this, thanks!

Using Bootsnap 1.4.4, Ruby 2.6.3, Bundler 1.17.2, Rails 5.2.3 on macOS 10.14.5.

**Comment by etellezp** [comment]
Hello sedubois, I was also having a lot of problems with bootsnap and I was getting a uninitialized constant User (NameError) while trying to run a rails g model User.
The problem was solved by upgrading Bundler to 2.0.2

**Comment by sedubois** [comment]
Thanks! Indeed due to my report I realized I could update to the latest bundler, which I then did update to 2.0.2, but I still got the errors afterwards a few times. I will monitor in the next days to see if they somehow disappear (maybe something is still cached somewhere on my machine...).

**Comment by sedubois** [comment]
I can confirm that the issue is still present as before with bundler 2.0.2.

**Comment by sedubois** [comment]
Worth noting that the issue fixes itself (at least in some cases) by just waiting long enough:
- start rails server
- visit /signup page, get "uninitialized constant Users"
- wait 5 seconds
- visit /signup page, get "uninitialized constant Users" again
- wait more than one minute
- visit /signup page, it then loaded correctly

As I only observe the issue in development, maybe this is not due to Bootsnap but to Spring? (using Spring 2.1.0)

**Comment by casperisfine** [comment]
Closing as non-reproducible.
