### ISSUE TITLE
date_core (LoadError)

### ISSUE THREAD

**Issue by rodolfospalenza** [Shopify/bootsnap#86]
Hello,

I tried install the bootsnap gem in my monolithic project to reduce the boot time but I receive the date_core (LoadError) that I didn't find much about this error.

* macOS Sierra 10.12.6
*  rvm
* ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin16]
* rails 4.2.8 

```ruby
# config/boot.rb

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap/setup'
```

```
$ rails s
/Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require': cannot load such file -- date_core (LoadError)
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rodolfo/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/date.rb:3:in `<top (required)>'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rodolfo/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/time.rb:1:in `<top (required)>'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/rack-1.6.5/lib/rack/utils.rb:6:in `<top (required)>'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/rack-1.6.5/lib/rack.rb:95:in `<module:Rack>'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/rack-1.6.5/lib/rack.rb:12:in `<top (required)>'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/actionpack-4.2.8/lib/action_dispatch.rb:29:in `<top (required)>'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/railties-4.2.8/lib/rails/commands/server.rb:3:in `<top (required)>'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:73:in `server'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rodolfo/.rvm/gems/ruby-2.2.5@bioritmo--smart-system/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from bin/rails:4:in `<main>'
```

The rails c command give me the same error.

Thanks for your help.

**Comment by volkanunsal** [comment]
Maybe restarting `spring` will help.

**Comment by Aileen-Cacayorin** [comment]
I'm having the same problem and restarting spring is not working as a solution. @rodolfospalenza did you ever find a fix?

**Comment by rodolfospalenza** [comment]
No @Aileen-Cacayorin, for while I add environment variable that when setted, will enable bootsnap.

**Comment by burke** [comment]
Hm, so it's loading `date.rb` from `RbConfig::CONFIG['libdir']`, which, in my installation, loads `date_core.bundle` from another dir on the load path...

```
$ irb -rtime
irb(main):001:0> $".select { |p| p =~ /date_core.bundle$/ }
=> ["/opt/rubies/2.2.5/lib/ruby/2.2.0/x86_64-darwin17/date_core.bundle"]
irb(main):002:0> $:.select { |p| p =~ /-darwin/ }
=> ["/opt/rubies/2.2.5/lib/ruby/site_ruby/2.2.0/x86_64-darwin17", "/opt/rubies/2.2.5/lib/ruby/vendor_ruby/2.2.0/x86_64-darwin17", "/opt/rubies/2.2.5/lib/ruby/2.2.0/x86_64-darwin17"]
```

I guess I'd be curious to see what those do on your machine -- and also curious to see what happens if you remove the bootsnap cache, probably at `tmp/cache/bootsnap-load-path-cache` and try again.

**Comment by burke** [comment]
I bet this is fixed by 1.3.0. Please don't hesitate to re-open if I'm wrong.

**Comment by dipakdipak** [comment]
The issue still persists. I have ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20].
But it still have the same error:
dlsym(0x7ff98c4df8f0, Init_date_core): symbol not found - /Library/Ruby/Gems/2.6.0/gems/date-3.1.1/lib/date_core.bundle (LoadError)

I had just run the command `pod -v` on my Mac Book Air terminal. 
Please help.
